lib/turnStile_web/router.ex
defmodule TurnStileWeb.Router do
  use TurnStileWeb, :router

  import TurnStileWeb.AdminAuth

  import TurnStileWeb.EmployeeAuth
  import TurnStileWeb.UserAuth
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TurnStileWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_employee
    plug :fetch_current_admin
    plug :fetch_current_user
    plug :require_non_expired_user_session
    # used in template
    plug TurnStileWeb.Plugs.RouteType, "non-admin"
    plug TurnStileWeb.Plugs.EmptyParams

  end

  pipeline :api do
    plug :accepts, ["json"]

    post "/sms_messages", TurnStileWeb.AlertController, :receive_sms_alert
  end

  scope "/api", TurnStileWeb do
    pipe_through :api

    get "/triage", TestController, :get_fake_triage_json
  end
  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only employees to access it.
  # If your application does not have an employees-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TurnStileWeb.Telemetry
    end
  end

  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  if Mix.env() == :test do
  scope "/test" do
    pipe_through :browser

    post "/organizations/:id/employees/register",
         TurnStileWeb.TestController,
         :quick_register_employee

    # get "/", TurnStileWeb.TestController, :employee_register
    get "/organizations/:id/employees/register",
        TurnStileWeb.TestController,
        :employee_register_page
    end

  end

  scope "/", TurnStileWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  if (Mix.env() == :test ||  Mix.env()) == :dev do

      scope "/", TurnStileWeb do
        pipe_through :browser

        get "/clear_sessions", FunctionsController, :clear_sessions
        get "/get_sessions", FunctionsController, :get_sessions
        get "/set_cookie", FunctionsController, :set_cookie
        get "/get_cookies", FunctionsController, :get_cookies
        get "/delete_cookie", FunctionsController, :delete_cookie
      end

  end

  ## Authentication routes

  scope "/organizations/:id", TurnStileWeb do
    pipe_through [:browser, :redirect_if_employee_is_authenticated]

    get "/employees/log_in", EmployeeSessionController, :new
    post "/employees/log_in", EmployeeSessionController, :create
    get "/employees/reset_password", EmployeeResetPasswordController, :new
    post "/employees/reset_password", EmployeeResetPasswordController, :create
    get "/employees/reset_password/:token", EmployeeResetPasswordController, :edit
    put "/employees/reset_password/:token", EmployeeResetPasswordController, :update
  end

  scope "/organizations/:id", TurnStileWeb do
    pipe_through [:browser, :require_authenticated_employee]

    get "/employees/settings", EmployeeSettingsController, :edit
    put "/employees/settings", EmployeeSettingsController, :update
    get "/employees/settings/confirm_email/:token", EmployeeSettingsController, :confirm_email

  end

  scope "/organizations/:id", TurnStileWeb do
    pipe_through [
      :browser,
      :require_register_access_employee
    ]

    get "/employees/register", EmployeeRegistrationController, :new
    post "/employees/register", EmployeeRegistrationController, :create
  end

  scope "/organizations/:id", TurnStileWeb do
    pipe_through [:browser]
    delete "/employees/log_out", EmployeeSessionController, :delete
    get "/employees/setup/:token", EmployeeConfirmationController, :setup #after employee creared, email URL directs them here viareply email link
    post "/employees/confirm/:token", EmployeeConfirmationController, :update
    put "/employees/confirm/:token", EmployeeConfirmationController, :update
  end

  scope "/", TurnStileWeb do
    pipe_through [:browser, :require_authenticated_employee]

    resources "/organizations", OrganizationController, except: [:show, :index, :new, :create] do
      # show, delete - TODO extract these since no point to nest
      resources "/employees", EmployeeController, except: [:new, :edit, :update, :index, :show]
    end

    live "/organizations/:organization_id/employees/:employee_id/users/", UserLive.Index, :index

    live "/organizations/:organization_id/employees/:employee_id/users/new", UserLive.Index, :new

    live "/organizations/:organization_id/employees/:employee_id/users/insert", UserLive.Index, :insert

    live "/organizations/:organization_id/employees/:employee_id/users/select", UserLive.Index, :select

    live "/organizations/:organization_id/employees/:employee_id/users/search", UserLive.Index, :search

    live "/organizations/:organization_id/employees/:employee_id/users/display_existing_users", UserLive.Index, :display_existing_users

    live "/organizations/:organization_id/employees/:employee_id/users/:id",
      UserLive.Show,
      :show

      live "/organizations/:organization_id/employees/:employee_id/users/:id/edit_show",
      UserLive.Show,
      :edit

      live "/organizations/:organization_id/employees/:employee_id/users/:id/alert",
        UserLive.Index,
        :alert, as: :organization_employee_user_alert


  end
  # user only in dev for testing - to quick submit a pubsub to index
  if Mix.env() in [:dev, :test] do
      # user filling out registation via self form
    scope "/organizations/:id/users/register/quick-test", TurnStileWeb do
      pipe_through [:browser, :redirect_if_user_is_authenticated]
      # check token; render form
      get "/:token", UserRegistrationController, :quick_new
      # user self form submit
      post "/:token",
      UserRegistrationController, :quick_send
    end
  end
  # user verification home page
  scope "/code", TurnStileWeb do
    pipe_through [:browser]
    get "/", UserRegistrationController, :index
    post "/", UserRegistrationController, :new
  end
  # user filling out registation via self form
  scope "/organizations/:id/users/register/", TurnStileWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    # check token; render form
    get "/:token", UserRegistrationController, :new
    # user self form submit
    post "/:token",
    UserRegistrationController, :handle_create
  end

  scope "/organizations/:organization_id/users", TurnStileWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    # user clicks link in email
    # first validate token is linked to user
    # second check organization matches the URL
    # third user login and redirect to :new
    get "/:user_id/:token", UserAuth, :handle_validate_email_token
  end

  scope "/organizations/:organization_id/users", TurnStileWeb do
    pipe_through [:browser, :require_authenticated_user,
    :ensure_organization_matches_current_user,
    :ensure_user_id_param_matches_current_user
  ]
    # redirect here after prev :ok
    get "/:user_id", UserSessionController, :new
    # when logout button is clicked
    delete "/:user_id/log_out", UserSessionController, :delete
    # sends conf/cancel buttons request on page
    post "/:user_id", UserConfirmationController, :update

  end

  # employee edit and update req write access
  scope "/organizations/:organization_id/employees/:id", TurnStileWeb do
    pipe_through [:browser,
    :require_authenticated_employee, :require_edit_access_employee]

    get "/edit", EmployeeController, :edit
    put "/edit", EmployeeController, :update
  end

  # /employees AUTHENCIATED
  scope "/organizations/:organization_id/", TurnStileWeb do
    pipe_through [
      :browser,
      :require_authenticated_employee,
      :require_edit_access_employee
    ]
  # employee edit action - req e access
    get "/employees", EmployeeController, :index, as: :organization_employee
  end

  scope "/organizations/:organization_id/employees/:id", TurnStileWeb do
    pipe_through [
      :browser,
      :require_authenticated_employee,
      :require_is_admin_employee
    ]
  # show to employee admin and up only
    get "/", EmployeeController, :show, as: :organization_employee

    get "/employees/confirm", EmployeeConfirmationController, :new
  end

  # /organizations NON_AUTHENCIATED
  scope "/organizations", TurnStileWeb do
    pipe_through :browser

    get "/search", OrganizationController, :search_get
    post "/search", OrganizationController, :search_post

    get "/new", OrganizationController, :new
    post "/new", OrganizationController, :handle_new
    post "/", OrganizationController, :create

    get "/:id", OrganizationController, :show
  end

  ## Admin routes

  scope "/organizations", TurnStileWeb do
    pipe_through [:browser, :require_authenticated_admin]
    # only admins can see all organizations
    get "/", OrganizationController, :index
  end

  scope "/", TurnStileWeb do
    pipe_through [:browser, :redirect_if_admin_is_authenticated]

    get "/admin/register", AdminRegistrationController, :new
    post "/admin/register", AdminRegistrationController, :create
    get "/admin/log_in", AdminSessionController, :new
    post "/admin/log_in", AdminSessionController, :create
    get "/admin/reset_password", AdminResetPasswordController, :new
    post "/admin/reset_password", AdminResetPasswordController, :create
    get "/admin/reset_password/:token", AdminResetPasswordController, :edit

lib/turnStile_web/live/components/alert_component/alert_panel_component.ex
  defmodule TurnStileWeb.AlertPanel do
  @doc"""
  Alert Live Component
  - there is no solo view for this page, it is only a modal
  - this liveView controls all logic for the alert panel modal
  - is opened from inside index liveView
  """
  use TurnStileWeb, :live_component
  alias TurnStile.Alerts
  alias TurnStile.Alerts.Alert
  alias TurnStileWeb.AlertUtils
  @json TurnStile.Utils.read_json("alert_text.json")

  @impl true
  def update(props, socket) do

    %{id: user_id, current_employee: _current_employee, user: user} = props

    alerts = Alerts.get_alerts_for_user(user_id)
    # IO.inspect(props, label: "props")
    # build default alert attrs to start, just a starting setting
    sms_attrs =
      Alerts.build_alert_specfic_attrs(
        user,
        AlertCategoryTypesMap.get_alert("CUSTOM"),
        AlertFormatTypesMap.get_alert("SMS"),
        title:  "Recieving TurnStile Alert"
      )

    changeset = Alerts.create_new_alert(%Alert{}, sms_attrs,true)
    # IO.inspect(changeset, label: "changeset in update")
    {:ok,
     socket
     |> assign(props)
     |> assign(:json, @json)
     |> assign(:alerts, alerts)
     |> assign(:title, set_title(props.panel)) # set sub-titles in panels
     |> assign(:page_title, "Alert Panel") # set  main page title
     |> assign(:changeset, changeset)}
  end

  @impl true
  # only fires on change-handles changing the form based on radio button selection
  def handle_event("radio_click", params, socket) do
    # IO.inspect("toggle_alert_form", label: "toggle_alert_form")
    # IO.inspect(params, label: "params")
    alert_params = Map.get(params, :alert) || Map.get(params, "alert")

    # check for changes when radio click
    if alert_params && Map.has_key?(socket.assigns.changeset, :data) do
      # IO.inspect(alert_params, label: "alert_params")
      # check which type of alert to change
      cond do
        # radio - flip to email form
        alert_params["alert_format"] === AlertFormatTypesMap.get_alert("EMAIL") ->

          # IO.inspect(socket.assigns.changeset, label: "click HERE radio")
          email_attrs =
            Alerts.build_alert_specfic_attrs(
              socket.assigns.user,
              AlertCategoryTypesMap.get_alert("CUSTOM"),
              AlertFormatTypesMap.get_alert("EMAIL"),
              from: alert_params["from"],
              to: alert_params["to"],
              title: "#{@json["alerts"]["request"]["email"]["initial"]["title"]}",
              body: "#{@json["alerts"]["request"]["email"]["initial"]["body"]}"

            )
          # sets up changeset for template use
          changeset =
            socket.assigns.changeset.data
            |> Alerts.change_alert(email_attrs, true)

          # IO.inspect(changeset, label: "changeset HERE radio")

          {:noreply, assign(socket, :changeset, changeset)}

        # end
        alert_params["alert_format"] === AlertFormatTypesMap.get_alert("SMS") ->
          # IO.inspect(alert_params, label: "SMS")

          sms_attrs =
            Alerts.build_alert_specfic_attrs(
              socket.assigns.user,
              AlertCategoryTypesMap.get_alert("CUSTOM"),
              AlertFormatTypesMap.get_alert("SMS")
            )

          changeset =
            socket.assigns.changeset.data
            |> Alerts.change_alert(sms_attrs, true)

          # IO.inspect(changeset, label: "changeset in validate")

          {:noreply, assign(socket, :changeset, changeset)}

        #  end
        true ->
          {:noreply, socket}
      end
    end
  end

  # # handle form change events - typing
  def handle_event("form_changes", params, socket) do
    alert_params = Map.get(params, :alert) || Map.get(params, "alert")
    # IO.inspect(socket.assigns.changeset, label: "socket.assigns.changeset")
    cond do
      # flip to email form
      alert_params["alert_format"] === AlertFormatTypesMap.get_alert("EMAIL") ->
        # IO.inspect(socket.assigns.changeset, label: "socket.assigns.changeset IN")
        # manually reassign category
        alert_params = Map.put(alert_params, "alert_category", AlertCategoryTypesMap.get_alert("CUSTOM"))
        # IO.inspect(alert_params, label: "PPP")
        # build new alert that is an email

        # enforce form validations here on email alert
        changeset =
          socket.assigns.changeset.data
          |> Alerts.change_alert(alert_params, true)

        IO.inspect(changeset, label: "changeset HERE2")

        {:noreply, assign(socket, :changeset, changeset)}

      alert_params["alert_format"] === AlertFormatTypesMap.get_alert("SMS") ->
        # IO.inspect(alert_params, label: "SMS")
        # manually reassign category
        alert_params = Map.put(alert_params, "alert_category", AlertCategoryTypesMap.get_alert("CUSTOM"))

        # enforce form validations here on sms alert
        changeset =
          socket.assigns.changeset.data
          |> Alerts.change_alert(alert_params, true)

        # IO.inspect(changeset, label: "changeset in validate")

        {:noreply, assign(socket, :changeset, changeset)}

      true ->
        {:noreply, socket}
    end
  end

  # send alert from custom dispatch form
  def handle_event("send_custom_alert", %{"alert" => alert_params}, socket) do
     # manually add category
      alert_params = Map.put(alert_params, "alert_category", AlertCategoryTypesMap.get_alert("CUSTOM"))
      changeset = Alerts.create_new_alert(%Alert{}, alert_params, true)
      AlertUtils.handle_sending_alert("send_custom_alert",
       changeset, socket)
  end

  defp set_title(panel_prop) do
    if panel_prop === "history" do
      "Alert History"
    else
      "Alert Dispatch"
    end
  end
end

lib/turnStile_web/live/components/pop_up_component/pop_up_block_component.ex
defmodule TurnStileWeb.PopUpBlock do
  use Phoenix.Component
  alias Phoenix.LiveView.JS

  @moduledoc """
  PopUpBlock Live Component
  - single item not in a list
  - for use when only a sinlge block is required
  """
  def render(assigns) do
    message_id = "message-#{assigns.id}"
    ~H"""
    <div id={message_id}class="popup  alert alert-danger">
    <div class="popup-header">
     <h3><%= assigns[:popup_title] %></h3>
      <p>
        <%= assigns[:popup_body] %>
      </p>
    </div>
      <div class="popup-body">
        <div class="pop-col">
        </div>
        <div class="pop-col">
          <button phx-click="user_alert_match_review" title="Review user before accept">Review</button>
          <button phx-click="user_alert_match_reject"  title="Reject and delete incoming response" data-confirm="This cannot be undone. Are you sure?">Reject</button>
        </div>
        <div class="pop-col">
        <a href="#" class="phx-modal-close" phx-click={hide_popup(message_id)} title="Ignore Message">✖</a>
        </div>
      </div>
    </div>
    """
    end
  # @impl
  # def handle_event("send_data_to_parent", %{value: _value}, socket) do
  #   # IO.inspect(socket.assigns, label: "send_data_to_parent")
  #   send_data_to_parent(socket)
  #   {:noreply, socket}
  # end
  def hide_popup(popup_id) do
    %JS{}
    |> JS.hide(transition: "fade-out", to: "##{popup_id}")
  end
end

lib/turnStile_web/live/user_live/form_component.html.heex
<div>

  <.form
    let={f}
    for={@changeset}
    id="user-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
    <%!-- TODO - fix this later - right now fires immmediately --%>
    <%!-- <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
    <% end %> --%>
    <main class="container">
      <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>
      <p class="alert alert-success" role="alert"
          phx-click="lv:clear-flash"
          phx-value-key="info"><%= live_flash(@flash, :success) %></p>
      <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>
    </main>

   <%= label f, :first_name %>
    <%= text_input f, :first_name %>
    <%= error_tag f, :first_name %>

    <%= label f, :last_name %>
    <%= text_input f, :last_name %>
    <%= error_tag f, :last_name %>

    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>

    <%= label f, :phone %>
    <%= text_input f, :phone %>
    <%= error_tag f, :phone %>

    <%= label f, :health_card_num %>
    <%= number_input f, :health_card_num %>
    <%= error_tag f, :health_card_num %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..."
      %>
    </div>
  </.form>
</div>

lib/turnStile_web/live/user_live/index.html.heex
<%= if @live_action in [:index] do %>
  <%= if TurnStile.Utils.is_list_greater_that_1?( @user_registration_messages) do %>
      <h2>Notification</h2>
  <% end %>
  <%= for message <- @user_registration_messages do %>
    <%= if TurnStileWeb.UserLive.Index.IndexUtils.show_user_registration_message(message, @current_employee.current_organization_login_id) do  %>
      <TurnStileWeb.PopUpItem.render
            module={TurnStileWeb.UserLive.TurnStileWeb.PopUpItem}
            id={elem(message, 0)}
            action={@live_action}
            popup_title={assigns[:popup_message_title]}
            popup_body={assigns[:popup_message_body]}
            popup_data={elem(message, 1)}/>

    <% end %>
  <% end %>
  <%= if TurnStile.Utils.is_list_greater_that_1?( @unmatched_SMS_users) do %>
    <h2>Notification</h2>
  <%!-- <% IO.inspect(user_tuple, label: 'XXX') %> --%>
      <TurnStileWeb.PopUpBlock.render
        module={TurnStileWeb.UserLive.TurnStileWeb.UserLive.PopUpBlock}
        current_employee={@current_employee}
        id={"unmatched_SMS_users_popup"}
        action={@live_action}
        popup_title={assigns[:popup_hero_title]}
        popup_body={assigns[:popup_hero_body]}
        popup_data={nil}
        />
    <% end %>
  <% end %>
<h1>Listing Users</h1>
<%!-- block re-renders until back to index - else child will reload --%>
  <%!-- <% IO.inspect(@unmatched_SMS_users, label: 'XXX') %> --%>

  <%!-- <%= if @toggle_popup do %>
  <% end %> --%>
  <%!-- list of possible modals opening from index --%>
  <%= if @live_action in [:new, :insert, :select] do %>
    <.modal return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}>
      <.live_component
        module={TurnStileWeb.UserLive.UpsertFormComponent}
        id={if assigns[:user] && Map.get(assigns[:user], :id) ,do: assigns[:user].id, else: :new}~
        live_action={@live_action}
        current_employee={@current_employee}
        user={assigns[:user]}
        subtitle={assigns[:subtitle]}
        page_title={@page_title}
        user_changeset={assigns[:user_changeset]}
        code={assigns[:code]}
        return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}
      />
    </.modal>
    <% end %>
    <%= if @live_action in [:alert] do %>
      <.modal return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}>
        <.live_component
          module={TurnStileWeb.AlertPanel}
          id={@user.id || :new}~
          action={@live_action}
          current_employee={@current_employee}
          user={@user}
          panel={@panel}
          page_title="Alerts"
          return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}
        />
      </.modal>
    
      <span><%= live_patch "Back", to: Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id) %></span>
    <% end %>
    <%= if @live_action in [:search, :display_existing_users] do %>
      <.modal return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}>

        <.live_component
          module={TurnStileWeb.UserLive.SearchComponent}
          id={:search}
          action={@live_action}
          current_employee={@current_employee}
          page_title={@page_title}
          return_to={Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id)}
        />
        <.live_component
          module={TurnStileWeb.UserLive.DisplayUsersList}
          users={assigns[:existing_users_found] || []}
          user_changeset={assigns[:user_changeset]}
          search_field_name={@search_field_name}
          search_field_value={@search_field_value}
          id={:display}
          live_action={@live_action}
          current_employee={@current_employee}
          page_title={@page_title}
          display_message={@display_message}
          display_instruction={@display_instruction}
          display_type={assigns[:display_type]}
          return_to={@return_to}
        />
      </.modal>
    
      <span><%= live_patch "Back", to: Routes.user_index_path(@socket, :index, @current_employee.current_organization_login_id, @current_employee.id) %></span>
    <% end %>

    <ul>
    <%= if TurnStileWeb.EmployeeAuth.has_user_add_permissions?(nil, @current_employee) do %>
      <li><%= live_patch "Add_New_User", to: Routes.user_index_path(@socket, :new, @current_employee.current_organization_login_id, @current_employee.id) %></li>

    <% end %>

     <li><%= live_patch "Search_For_User", to: Routes.user_index_path(@socket, :search, @current_employee.current_organization_login_id, @current_employee.id) %></li>

    </ul>
  <table>
    <thead>
      <tr>

        <th>Active?</th>
        <th>Status</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Contact</th>
        <th>Health #</th>
      </tr>
    </thead>
    <tbody id="users">
      <%= for user <- @users do %>

        <tr id={"user-#{user.id}"}>
          <td><%= user.is_active? %></td>
          <td title="cancelled users remain in feed for 30 mins"><%= String.capitalize(user.user_alert_status) %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <%= if user.alert_format_set === AlertFormatTypesMap.get_alert("EMAIL") do %>
            <td><%= user.email %></td>
          <% else %>
            <td><%= user.phone %></td>
          <% end %>
          
          <td><%= user.health_card_num %></td>

          <td>
            <span>
            <%= if user.alert_format_set === AlertFormatTypesMap.get_alert("EMAIL") do %>
                <button
                  title="send initial email alert"
                  class={"btn btn-primary #{if !user.email do 'disable' end}"}
                  phx-click={:send_initial_alert} phx-value-user-id={user.id}, phx-value-alert-format={AlertFormatTypesMap.get_alert("EMAIL")}> 
                    Send Email Alert
                </button>
            <% else %>
                <button
                  title="send initial SMS alert"
                  class={"btn btn-primary #{if !user.phone do 'disable' end}"}
                  phx-click={:send_initial_alert} phx-value-user-id={user.id}, phx-value-alert-format={AlertFormatTypesMap.get_alert("SMS")}> 
                  Send SMS Alert
                </button>

            <% end %>
            </span>
              <span>
                <%= live_patch "Custom_Alert", to: Routes.organization_employee_user_alert_path(@socket, :alert, @current_employee.current_organization_login_id, @current_employee.id, user.id,  %{panel: "dispatch"}) %>
              </span>

              <span>
                <%= live_patch "Alert_History", to: Routes.organization_employee_user_alert_path(@socket, :alert, @current_employee.current_organization_login_id, @current_employee.id, user.id,  %{panel: "history"}) %>
              </span>
          </td>

          <td>
            <span><%= live_redirect "Show", to: Routes.user_show_path(@socket, :show, @current_employee.current_organization_login_id, @current_employee.id, user) %></span>
          </td>

          <%= if TurnStileWeb.EmployeeAuth.has_user_delete_permissions?(@socket, @current_employee) do %>
          <td>
            <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: user.id, data: [confirm: "Are you sure?"] %></span>
          </td>
          <% end %>
          <%= if TurnStileWeb.EmployeeAuth.has_user_remove_permissions?(@socket, @current_employee) do %>
          <td>
            <span><%= link "Remove", to: "#", phx_click: "remove", phx_value_id: user.id, data: [confirm: "Deactivate and remove?"] %></span>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

lib/turnStile_web/live/user_live/show.html.heex
<h1>Show User</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.user_show_path(@socket, :show, @current_employee.current_organization_login_id, @current_employee.id, @user)}>
    <.live_component
      module={TurnStileWeb.UserLive.UpsertFormComponent}
      id={@user.id}
      user_changeset={assigns[:user_changeset]}
      page_title={@page_title}
      live_action={@live_action}
      subtitle={assigns[:subtitle]  }
      user={@user}
      current_employee={@current_employee}
      return_to={Routes.user_show_path(@socket, :show, @current_employee.current_organization_login_id, @current_employee.id, @user)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Phone:</strong>
    <%= @user.phone %>
  </li>

  <li>
    <strong>Date of Birth:</strong>
    <%= @user.date_of_birth %>
  </li>

  <li>
    <strong>Health card num:</strong>
    <%= @user.health_card_num %>
  </li>

  <li>
    <strong>Main Alert Type:</strong>
    <%= @user.alert_format_set %>
  </li>
  <li>
    <strong>Added at:</strong>
    <% {:ok, shifted_datetime} = TurnStile.Utils.shift_naive_datetime(@user.inserted_at, @current_employee.timezone) %>
      <%= "#{shifted_datetime.year}-#{shifted_datetime.month}-#{shifted_datetime.day} #{shifted_datetime.hour}:#{shifted_datetime.minute}:#{shifted_datetime.second} #{if shifted_datetime.hour >= 12, do: "PM", else: "AM"}" %>
  </li>
  <li>
    <strong>Last Updated at:</strong>
    <% {:ok, shifted_datetime} = TurnStile.Utils.shift_naive_datetime(@user.updated_at, @current_employee.timezone) %>
      <%= "#{shifted_datetime.year}-#{shifted_datetime.month}-#{shifted_datetime.day} #{shifted_datetime.hour}:#{shifted_datetime.minute}:#{shifted_datetime.second} #{if shifted_datetime.hour >= 12, do: "PM", else: "AM"}" %>
  </li>

</ul>
 <%= if TurnStileWeb.EmployeeAuth.has_user_edit_permissions?(nil, @current_employee) do %>
  <span><%= live_patch "Edit", to: Routes.user_show_path(@socket, :edit, @current_employee.current_organization_login_id, @current_employee.id, @user) %></span>
<% end %>
<span><%= live_redirect "Back", to: Routes.user_index_path(@socket, :index, @organization_id, @employee_id) %></span>